version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/raviqqe/gherkin2markdown
    steps:
      - checkout

      - run:
          name: Dependencies
          command: |
              go get -u github.com/alecthomas/gometalinter
              gometalinter --install
              go get -d -t ./...

      - run:
          name: Lint
          command: gometalinter

      - run:
          name: Build
          command: go build

      - run:
          name: Test
          command: go test -covermode atomic -coverprofile coverage.txt

      - run:
          name: Coverage Report
          command: curl -s https://codecov.io/bash | bash
